---
title: "Model"
format: html
execute: 
  echo: false
---

```{r}
#| message: false
#| label: setup
#| warning: false

library(tidyverse)
library(primer.data)
library(brms)
library(tidybayes)
library(gtsummary)
library(knitr)
```


```{r}
#| message: false
#| cache: true

x <- read_csv("data/ow_data.csv")

x <- x |> 
  mutate(win_rate = as.numeric(as.character(`Win Rate, %`)), 
         elim_rate = as.numeric(as.character(`Eliminations / 10min`)), 
         death_rate = as.numeric(as.character(`Deaths / 10min`)),
         KDA = as.numeric(as.character(`KDA Ratio`)),
         dmg_rate = as.numeric(as.character(`Damage / 10min`)),
         heal_rate = as.numeric(as.character(`Healing / 10min`)))

x <- x |> 
  select(win_rate, elim_rate, death_rate, KDA, dmg_rate, heal_rate) |>
  drop_na()
```

The formula used for the model is 
$$ \text{win_rate} = \beta_0 + \text{elim_rate} \beta_1 + \text{death_rate} \beta_2 + \text{KDA} \beta_3 + \text{dmg_rate} \beta_4 + \text{heal_rate} \beta_5 $$


```{r}
# Data
data <- data.frame(
  Coefficient = c( "elim_rate", "death_rate", "KDA", "dmg_rate", "heal_rate"),
  Estimate = c(-0.90, 5.84, 4.50, 0.00, 0.00),
  Est.Error = c(0.28, 0.82, 0.60, 0.00, 0.00),
  l_95_CI = c( -1.46, 4.22, 3.30, -0.00, -0.00),
  u_95_CI = c( -0.35, 7.45, 5.62, 0.00, 0.00)
)

# Calculate Beta
data$Beta <- (data$u_95_CI - data$l_95_CI) / 2

# Create the table
kable(data[, c("Coefficient", "l_95_CI", "u_95_CI", "Beta")],
      col.names = c("Coefficient", "l-95% CI", "u-95% CI", "Beta"))
```

As seen in the table above we can see that win rate is most affected by KDA and death_rate, while least affected by dmg_rate and heal_rate. 

```{r}
#| cache: true
#| message: false

fit_model <- brm(formula = win_rate ~ elim_rate + death_rate + KDA + dmg_rate + heal_rate,
                 data = x,
                 family = gaussian(),
                 refresh = 0,
                 silent = 2,
                 seed = 9)
```

```{r}
fixef(fit_model)
pp_check(fit_model)
```



